#ifndef BITCOIN_CHAINPARAMSSEEDS_H
#define BITCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the bitcoin network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 */
static const uint8_t chainparams_seed_main[1] = {};

static const uint8_t chainparams_seed_signet[1] = {};

static const uint8_t chainparams_seed_test[1] = {};

static const uint8_t chainparams_seed_testnet4[1] = {};
#endif // BITCOIN_CHAINPARAMSSEEDS_H